@baseURL = http://localhost:3000
### Rota pública para listagem de pets 'available'
GET {{baseURL}}/pets/available
Content-Type: application/json

### Cadastro de novo usuário (register) sem role para testar criação com DEFAULT
POST {{baseURL}}/users
Content-Type: application/json

{
 "name": "João da Silva",
 "email": "novo@ifrs.edu.br",
 "password": "senha123",
 "phone": "54998185683"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/login
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123"
}

### Login do administrador (usuário já existente no banco)
POST {{baseURL}}/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "123456"
}

### Acesso ao painel (rota protegida, requer token de admin)
GET {{baseURL}}/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70
### Acesso à rota /pets/:id (rota protegida, requer token de admin)
GET {{baseURL}}/pets/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70
###Acesso ao cadastro de novo pet (rota protegida, requer token de admin) sem status para testar DEFAULT 

POST {{baseURL}}/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70
Content-Type: application/json

{
    "name": "Max",
    "age": 2,
    "species": "Cão poodle",
    "size": "small",
    "description": "cão dócil"
}

###Acesso à atualização do cadastro do pet (rota protegida, requer token de admin)

PUT {{baseURL}}/pets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70
Content-Type: application/json

{
    "name": "Rex",
    "age": 4,
    "species": "Cão SRD",
    "size": "large",
    "status" : "available",
    "description": "cão de guarda vacinado"
}

###Acesso à rota DELETE pets (rota protegida, requer token de admin)
DELETE {{baseURL}}/pets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70


### Acesso à todos os users (rota protegida, requer token de admin)
GET {{baseURL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwMzUzOCwiZXhwIjoxNzUwODA3MTM4fQ.KvijVk7L_f4kXNQgEawtxu-duw0TnkuOv3YSikUAp70

### Acesso a um user específico (rota protegida, requer token de admin ou o próprio usuário)
GET {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUwODA0MDU5LCJleHAiOjE3NTA4MDc2NTl9.mm8J07qOoW9zyUG_ZVrvginbMIo1ooOVuP5IGGj4TnU


### Acesso à rota PUT users/:id (rota protegida, requer token de admin ou o próprio usuário)
PUT {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUwODA0MDU5LCJleHAiOjE3NTA4MDc2NTl9.mm8J07qOoW9zyUG_ZVrvginbMIo1ooOVuP5IGGj4TnU
Content-Type: application/json

{
"name": "João da Silva",
"email": "novo@ifrs.edu.br",
"password": "senha123",
"phone": "54998185683", 
"role": "admin"
}

### Acesso à rota DELETE users (rota protegida, requer token de admin)
DELETE {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjQsInJvbGUiOm51bGwsImlhdCI6MTc1MDc4OTI5MCwiZXhwIjoxNzUwNzkyODkwfQ.A4Y4nUYhUstDgx-MslGRuXEbpxtUVoZRMUvYRuLebSg


### Acesso à rota GET /adoptions (rota protegida, requer token de admin)
GET {{baseURL}}/adoptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDgwNzUzMiwiZXhwIjoxNzUwODExMTMyfQ.SdpvtOYv7kY6yNZiuZ8WDgqGFeeycvtxwYOXYA5mmco

###Acesso à rota POST /adoptions (rota protegida, requer token de adopter)
POST {{baseURL}}/adoptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUwODA0MDU5LCJleHAiOjE3NTA4MDc2NTl9.mm8J07qOoW9zyUG_ZVrvginbMIo1ooOVuP5IGGj4TnU
Content-Type: application/json

{
    "pet_id": 9
}