@baseURL = http://localhost:3000
### Rota pública para listagem de pets 'available'
GET {{baseURL}}/pets/available
Content-Type: application/json

### Cadastro de novo usuário (register) sem role para testar criação com DEFAULT
POST {{baseURL}}/users
Content-Type: application/json

{
 "name": "João da Silva",
 "email": "novo@ifrs.edu.br",
 "password": "senha123",
 "phone": "54998185683"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/login
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123"
}

### Login do administrador (usuário já existente no banco)
POST {{baseURL}}/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "123456"
}

### Acesso ao painel (rota protegida, requer token de admin)
GET {{baseURL}}/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ

###Acesso ao pet especifico (requer token de admin)
GET {{baseURL}}/pets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ

###Acesso ao cadastro de novo pet (rota protegida, requer token de admin) sem status para testar DEFAULT 
POST {{baseURL}}/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ
Content-Type: application/json

{
    "name": "Maxwell",
    "age": 2,
    "species": "Cão border collie",
    "size": "medium",
    "description": "cão de companhia, vacinado"
}

###Acesso à atualização do cadastro do pet (rota protegida, requer token de admin)
PUT {{baseURL}}/pets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ
Content-Type: application/json

{
    "name": "Rex",
    "age": 4,
    "species": "Cão SRD",
    "size": "large",
    "status" : "adopted",
    "description": "cão de guarda vacinado"
}

###Acesso à rota DELETE pets (rota protegida, requer token de admin)
DELETE {{baseURL}}/pets/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ


### Acesso à todos os users (rota protegida, requer token de admin)
GET {{baseURL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzODcwNywiZXhwIjoxNzUxMjQyMzA3fQ.9e2oYKtzi8os_wv_UxAdlGLkuzdfBzuFXML1t-M370A
### Acesso a um user específico (rota protegida, requer token de admin ou o próprio usuário)
GET {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjUsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMjM1NTY2LCJleHAiOjE3NTEyMzkxNjZ9.HcsiUWMYgKNpmwTBh6UMuLefGJltURYc5hQWdO4T-IA


### Acesso à rota PUT users/:id (rota protegida, requer token de admin ou o próprio usuário)
PUT {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjUsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMjM1NTY2LCJleHAiOjE3NTEyMzkxNjZ9.HcsiUWMYgKNpmwTBh6UMuLefGJltURYc5hQWdO4T-IA
Content-Type: application/json

{
"name": "João da Silva",
"email": "novo@ifrs.edu.br",
"password":"senha123",
"phone": "54998185684", 
"role": "adopter"
}

### Acesso à rota DELETE users (rota protegida, requer token de admin)
DELETE {{baseURL}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIzNTAwNiwiZXhwIjoxNzUxMjM4NjA2fQ.oU4dkivm5jtikJxHYvIKCMM_32j4tu3A-TYYtqTEiOQ

### Acesso à rota GET /adoptions (rota protegida, requer token de admin)
GET {{baseURL}}/adoptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIyNjU3MCwiZXhwIjoxNzUxMjMwMTcwfQ.6hqhw9EV9phoCri7UpMyczavjqjjZkhVQLuUxwua6fM

###Acesso à rota POST /adoptions (rota protegida, requer token de adopter)
POST {{baseURL}}/adoptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTIyNjU3MCwiZXhwIjoxNzUxMjMwMTcwfQ.6hqhw9EV9phoCri7UpMyczavjqjjZkhVQLuUxwua6fM
Content-Type: application/json

{
    "pet_id": 2
}